import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="container my-5">
      <h2 className="mb-4">Terms and Conditions</h2>
      <p>Welcome to Pranayuv Technologies Private Limited...</p>
     Pranayuv Terms and Conditions
Welcome to Pranayuv Technologies Private Limited, a company incorporated under the laws of India, having its registered address at Room No.220, EEE Dept., V.R. Siddhartha College, Kanuru, Krishna, Vijayawada (rural), Andhra Pradesh, India, 520007, and bearing Corporate Identification Number (CIN) U62099AP2025PTC119012 (hereinafter referred to as “Pranayuv,” “Pranayuv technologies,” “We,” “Us,” “Our,” or the “Company”). These Terms and Conditions (“Terms”) govern your access to and use of our website and services (collectively referred to as the “Services”).
This document is an electronic record in terms of the Information Technology Act, 2000, and the rules thereunder as applicable, including the amended provisions pertaining to electronic records in various statutes. It is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which mandates the publication of rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name [www.pranayuv.com](http://www.pranayuv.com) (‘Website’), including any related mobile site and application (collectively referred to as the ‘Platform’).
By accessing or using the Platform or its Services, you agree to be bound by these Terms. If you do not agree, you must discontinue using the Services immediately. Your continued use constitutes acceptance of these Terms, which may be updated from time to time. These Terms represent a legally binding agreement between Pranayuv Technologies Private Limited (‘Company’) and any individual or entity (“User,” “You,” or “Your”) accessing or using our Services. Please read these Terms carefully before proceeding.

1. Definitions
   For the purposes of these Terms:
   •	“Company” refers to Pranayuv Technologies Private Limited, its affiliates, and subsidiaries.
   •	“Website” refers to all digital platforms owned, operated, or managed by the Company, including [www.pranayuv.com](http://www.pranayuv.com), its subdomains.
   •	“Services” include but are not limited to online tools, e-commerce functionalities, reservation systems, and customer support provided through the Website.
   •	“User” refers to any individual or entity accessing or using the Services.
   •	“Products” refer to the health care and associated services offered by the Company.
   •	“Content” refers to all text, images, videos, and other multimedia provided on the Website or through the Services.
2. Eligibility to Use
   To access or use our Services, you must meet the following criteria:
3. Age Requirement:
   You must be at least 18 years old to use our Services. By accessing our Website, you confirm that you are of legal age to form a binding contract under the laws of India. If you are a minor and wish to use or make transactions on our website, such actions may be carried out by your legal guardian or parent on your behalf. The Company reserves the right to deny access to the Website if it is discovered that you are under the age of 18 or if such information is brought to our attention.
4. Authority to Act:
   If You are accessing or using the Services on behalf of a company or organization, You warrant that You have the authority to bind such entity to these Terms.
5. Compliance with Laws:
   You agree to comply with all applicable laws, regulations, and guidelines while using our Services.
   The Company reserves the right to terminate or restrict access to its Services at any time if You violate any of the eligibility criteria.
6. User Obligations
   As a User of our Services, You agree to the following obligations:
7. Accuracy of Information:
   You are responsible for ensuring that all information provided by You while using our Services is accurate, complete, and up to date. For details on how we protect your personal data, please refer to our Privacy Policy.
8. Account Security:
   If You create an account with Us, You are solely responsible for maintaining the confidentiality of Your account credentials and for all activities occurring under Your account.
9. Prohibited Activities:
   You agree not to:
   •	Use the Services for any unlawful purpose.
   •	Engage in any activity that disrupts or interferes with the functioning of the Website or Services.
   •	Attempt to gain unauthorized access to any part of the Website, including accounts or systems belonging to other Users.
   •	Upload or transmit malicious software or harmful content.
10. Respect for Intellectual Property:
    You must respect the intellectual property rights of the Company and others while using the Website. You may not copy, reproduce, or distribute any Content without prior written consent.
    The Company reserves the right to investigate and take appropriate action, including legal recourse, against any User who violates these obligations.
11. Intellectual Property Rights
12. Ownership:
    All content, trademarks, logos, designs, graphics, images, text, and any other materials available on the Website (collectively, the “Content”) are the exclusive property of Pranayuv Technologies Private Limited or its licensors. The Content is protected under applicable intellectual property laws in India and internationally.
13. Limited License:
    The Company grants You a non-exclusive, non-transferable, revocable license to access and use the Website and Services strictly in accordance with these Terms. This license does not permit You to:
    •	Modify, copy, or create derivative works based on the Content.
    •	Reproduce or distribute the Content without prior written consent.
    •	Use the Content for any commercial purposes not expressly authorized by the Company.
14. Third-Party Intellectual Property:
    Any intellectual property owned by third parties and displayed on the Website remains the property of its respective owner(s). The Company does not grant any rights over such third-party intellectual property.
15. Pricing and Payments
16. Product Pricing:
    The prices displayed on the Website for products and services are subject to change at the Company’s sole discretion without prior notice. All prices are inclusive of applicable taxes unless specified otherwise.
17. Payment Methods:
    The Company accepts payments through authorized third-party payment gateways. By using these gateways, You agree to abide by their terms and conditions.
18. Order Confirmation:
    Upon successful payment, You will receive a confirmation email or notification with details of Your purchase. The Company reserves the right to cancel any order due to pricing errors, insufficient stock, or any other unforeseen circumstances.
19. Refunds, Returns, Cancellations, Shipping and Warranty:
    Refunds, returns, cancellations, shipping, and product warranties are governed by the Company’s Service Policies, accessible on the Website. Please review the Service Policies carefully before making a purchase or placing an order to understand the applicable terms and conditions.
20. User Responsibilities
21. Compliance with Laws:
    By using the Website, You agree to comply with all applicable local, state, national, and international laws and regulations. Any misuse or unauthorized use of the Website is strictly prohibited.
22. Account Security:
    You are responsible for maintaining the confidentiality of Your account credentials and are liable for all activities conducted through Your account. Notify the Company immediately if You suspect unauthorized access to Your account.
23. Prohibited Activities:
    Users are prohibited from:
    •	Uploading harmful, offensive, or illegal content to the Website.
    •	Attempting to access restricted areas of the Website or its servers.
    •	Using the Website for fraudulent, malicious, or unauthorized purposes.
24. Content Integrity:
    Users must not manipulate or interfere with the content, services, or functionality of the Website, including but not limited to introducing viruses, bots, or harmful codes.
25. Third-Party Services and Links
26. Third-Party Integration:
    The Website may integrate or provide links to third-party websites, services, or applications. These third-party platforms operate independently and are governed by their respective terms and privacy policies.
27. No Endorsement:
    The inclusion of links to third-party websites does not imply endorsement, sponsorship, or affiliation by the Company. The Company does not guarantee the accuracy, safety, or reliability of third-party services.
28. User Responsibility:
    By accessing third-party services or links through the Website, You agree to do so at Your own risk. The Company is not liable for any loss or damage resulting from Your interaction with third-party platforms.
29. Disclaimer of Warranties and Liability
30. “As Is” Basis & No Guarantee:
    The Website and its content are provided on an “as is” and “as available” basis without warranties of any kind, whether express or implied. The Company makes no guarantees regarding the accuracy, completeness, reliability, or timeliness of the Website’s content or functionality.
31. Exclusion of Liability:
    To the fullest extent permitted by applicable law, the Company, its directors, employees, agents, or affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, arising from:
    •	Your access to or use of the Website.
    •	Any errors, omissions, or inaccuracies in the Website’s content.
    •	Unauthorized access, use, or alteration of Your data.
32. Cumulative Liability:
    In any event, the total liability of the Company for all claims arising out of or related to the use of the Website shall not exceed the amount You have paid to the Company in the past three (3) months preceding the claim, if any, for accessing the Website or availing of its services.
33. Third-Party Impact:
    The Company assumes no liability for any third-party actions or content, including services or advertisements available through the Website.
34. Indemnification
35. User Responsibility: You agree to indemnify, defend, and hold harmless the Company, its affiliates, directors, officers, employees, and agents from and against any claims, liabilities, damages, losses, costs, and expenses, including reasonable attorney fees, arising out of:
    •	Your violation of these Terms and Conditions.
    •	Your misuse of the Website or its services.
    •	Any third-party claims resulting from Your actions or omissions while using the Website.
36. Notification: The Company reserves the right to assume exclusive defense and control of any matter otherwise subject to indemnification by You, in which case You agree to cooperate with the Company in asserting any available defenses.
37. Termination
38. Right to Terminate: The Company reserves the right to terminate or suspend Your access to the Website or any part of its services, with or without prior notice, for any reason, including but not limited to:
    •	Your breach of these Terms and Conditions.
    •	Non-payment of any applicable fees.
    •	Engagement in fraudulent, abusive, or unlawful activities.
39. User Obligations Upon Termination: Upon termination:
    •	All rights granted to You under these Terms and Conditions will immediately cease.
    •	You must stop all use of the Website and its services.
    •	Any obligations or liabilities incurred by You prior to termination shall remain enforceable.
40. Company’s Liability on Termination: The Company will not be liable for any loss or damage arising out of termination of Your access to the Website or its services.
41. Governing Law and Jurisdiction
42. Applicable Law:
    These Terms and Conditions shall be governed and construed in accordance with the laws of India.
43. Jurisdiction:
    Any disputes arising out of or in connection with these Terms and Conditions or the use of the Website shall be subject to the exclusive jurisdiction of the courts located in Vijayawada, Andhra Pradesh.
44. International Use:
    Users accessing the Website from outside India do so at their own risk and are responsible for compliance with local laws, if and to the extent applicable.
45. Force Majeure
46. Events Beyond Control: The Company shall not be held liable for any failure or delay in the performance of its obligations under these Terms and Conditions if such failure or delay is caused by events beyond its reasonable control, including but not limited to:
    •	Natural disasters, such as floods, earthquakes, and storms.
    •	War, terrorism, riots, strikes, or civil unrest.
    •	Government actions or regulations.
    •	Failures in telecommunications or internet infrastructure.
47. Notification: In case of a force majeure event, the Company will inform You of the situation as soon as reasonably possible and will make efforts to resume normal performance.
48. Severability
    If any part of these Terms and Conditions is found to be invalid, illegal, or unenforceable, such provision will be deemed modified or removed, and the remainder of the Terms and Conditions will remain in full force and effect.
49. Entire Agreement
    These Terms and Conditions, together with any documents expressly incorporated herein, constitute the entire agreement between You and the Company concerning the use of the Website and its services. Any prior or contemporaneous communications or agreements, whether written or oral, are superseded by this agreement.
50. Contact Us
    For any questions, complaints, or clarifications regarding any of our Services or Terms, or to exercise any of Your rights, please contact Us at: [info@pranayuv.com](mailto:info@pranayuv.com)
51. Updates to Terms
    Pranayuv Technologies reserves the right to modify or update these Terms at any time, with or without notice. We encourage users to periodically review this page for any changes. Any updates to the Terms will be effective immediately upon posting on this website, and continued use of the website following any changes constitutes acceptance of those updated Terms. If you disagree with any modifications, you should discontinue use of the site.


    </div>
  );
};

export default TermsAndConditions;
